gov_rek: False # varied across experiments
log_dir: "logs_dir/governed_ppo_trainer"
check_freq: 1000
trainer_policy: "MlpPolicy"
verbose: 0
total_timesteps: 200000
size: 5
gas: 7
randomize_world: False # varied across experiments
kernel_list: ["regular_gradient_kernel", "inverse_radial_kernel"]
mors_objective: ["regular_gradient_kernel"]
her_goal: False # fixed for all experiments
